name: Build

on:
  push:
    branches: [ 'main' ]

jobs:
  build:
    strategy:
      matrix:
        labels: [ ubuntu-large-disk, windows-large-disk ]
        python-version: [ '3.11' ]
    runs-on: ${{ matrix.labels }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Configure Git to use HTTPS for poetry git dependencies
        run: |
          git config --global url."https://github.com/".insteadOf git@github.com:

      - name: Install dependencies (Ubuntu)
        if: matrix.labels == 'ubuntu-large-disk'
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb python3-tk libcairo2-dev libxt-dev libgirepository1.0-dev python3-gi gobject-introspection gir1.2-gtk-3.0 gir1.2-appindicator3-0.1
          pip install poetry
          poetry self update
          poetry cache clear --all pypi
          poetry install --extras linux

      - name: Install dependencies (Windows)
        if: matrix.labels == 'windows-large-disk'
        run: |
          pip install poetry
          poetry install
          pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

      - name: Build with pyinstaller
        run: poetry run pyinstaller biocentral_server.spec

      - name: Copy additional files to dist directory (Ubuntu)
        if: matrix.labels == 'ubuntu-large-disk'
        run: |
          cp LICENSE dist/LICENSE
          cp README.md dist/README.md

      - name: Copy additional files to dist directory (Windows)
        if: matrix.labels == 'windows-large-disk'
        run: |
          copy LICENSE dist/LICENSE
          copy README.md dist/README.md

      - name: Upload build artifacts (Ubuntu)
        if: matrix.labels == 'ubuntu-large-disk'
        uses: actions/upload-artifact@v4
        with:
          name: biocentral_server_ubuntu
          path: dist

      - name: Upload build artifacts (Windows)
        if: matrix.labels == 'windows-large-disk'
        uses: actions/upload-artifact@v4
        with:
          name: biocentral_server_windows
          path: dist
