name: Build

on:
  push:
    branches: [ 'main' ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.11']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk libcairo2-dev libxt-dev libgirepository1.0-dev
        pip install poetry
        poetry install --extras linux

    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        pip install poetry
        poetry install
        pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

    - name: Build with pyinstaller
      run: poetry run pyinstaller biocentral_server.spec

    - name: Upload build artifacts (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v3
      with:
        name: biocentral_server_windows
        path: dist/biocentral_server.exe

    - name: Upload build artifacts (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v3
      with:
        name: biocentral_server_ubuntu
        path: dist/biocentral_server
