name: Release

on:
  workflow_run:
    workflows: [Build]
    types: [completed]
    branches: [main]

jobs:
  create_release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version
        id: get_version
        run: echo "::set-output name=version::$(grep 'version = ' pyproject.toml | awk -F'"' '{print $2}' | tr . -)"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: v${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Upload Ubuntu Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./biocentral_server_ubuntu-latest/biocentral_server_ubuntu-latest.zip
          asset_name: biocentral_server_ubuntu-${{ steps.get_version.outputs.version }}.zip
          asset_content_type: application/octet-stream

      - name: Upload Windows Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./biocentral_server_windows-latest/biocentral_server_windows-latest.zip
          asset_name: biocentral_server_windows-${{ steps.get_version.outputs.version }}.zip
          asset_content_type: application/octet-stream